/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface MockCadencePrecompileInterface extends Interface {
  getFunction(
    nameOrSignature: "revertibleRandom" | "setMockRandomValue"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "revertibleRandom",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setMockRandomValue",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "revertibleRandom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMockRandomValue",
    data: BytesLike
  ): Result;
}

export interface MockCadencePrecompile extends BaseContract {
  connect(runner?: ContractRunner | null): MockCadencePrecompile;
  waitForDeployment(): Promise<this>;

  interface: MockCadencePrecompileInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  revertibleRandom: TypedContractMethod<[], [string], "view">;

  setMockRandomValue: TypedContractMethod<
    [value: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "revertibleRandom"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setMockRandomValue"
  ): TypedContractMethod<[value: BigNumberish], [void], "nonpayable">;

  filters: {};
}
