/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  CadenceRandomConsumer,
  CadenceRandomConsumerInterface,
} from "../../../../../@onflow/flow-sol-utils/src/random/CadenceRandomConsumer";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "requestId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint64",
        name: "randomResult",
        type: "uint64",
      },
    ],
    name: "RandomnessFulfilled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "requestId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint64",
        name: "flowHeight",
        type: "uint64",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "evmHeight",
        type: "uint256",
      },
    ],
    name: "RandomnessRequested",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "requestId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint64",
        name: "flowHeight",
        type: "uint64",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "evmHeight",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "randomSource",
        type: "bytes32",
      },
    ],
    name: "RandomnessSourced",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "requestId",
        type: "uint256",
      },
    ],
    name: "canFulfillRequest",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class CadenceRandomConsumer__factory {
  static readonly abi = _abi;
  static createInterface(): CadenceRandomConsumerInterface {
    return new Interface(_abi) as CadenceRandomConsumerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): CadenceRandomConsumer {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as CadenceRandomConsumer;
  }
}
