/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../../common";

export interface CadenceRandomConsumerInterface extends Interface {
  getFunction(nameOrSignature: "canFulfillRequest"): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "RandomnessFulfilled"
      | "RandomnessRequested"
      | "RandomnessSourced"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "canFulfillRequest",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "canFulfillRequest",
    data: BytesLike
  ): Result;
}

export namespace RandomnessFulfilledEvent {
  export type InputTuple = [
    requestId: BigNumberish,
    randomResult: BigNumberish
  ];
  export type OutputTuple = [requestId: bigint, randomResult: bigint];
  export interface OutputObject {
    requestId: bigint;
    randomResult: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RandomnessRequestedEvent {
  export type InputTuple = [
    requestId: BigNumberish,
    flowHeight: BigNumberish,
    evmHeight: BigNumberish
  ];
  export type OutputTuple = [
    requestId: bigint,
    flowHeight: bigint,
    evmHeight: bigint
  ];
  export interface OutputObject {
    requestId: bigint;
    flowHeight: bigint;
    evmHeight: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RandomnessSourcedEvent {
  export type InputTuple = [
    requestId: BigNumberish,
    flowHeight: BigNumberish,
    evmHeight: BigNumberish,
    randomSource: BytesLike
  ];
  export type OutputTuple = [
    requestId: bigint,
    flowHeight: bigint,
    evmHeight: bigint,
    randomSource: string
  ];
  export interface OutputObject {
    requestId: bigint;
    flowHeight: bigint;
    evmHeight: bigint;
    randomSource: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CadenceRandomConsumer extends BaseContract {
  connect(runner?: ContractRunner | null): CadenceRandomConsumer;
  waitForDeployment(): Promise<this>;

  interface: CadenceRandomConsumerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  canFulfillRequest: TypedContractMethod<
    [requestId: BigNumberish],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "canFulfillRequest"
  ): TypedContractMethod<[requestId: BigNumberish], [boolean], "view">;

  getEvent(
    key: "RandomnessFulfilled"
  ): TypedContractEvent<
    RandomnessFulfilledEvent.InputTuple,
    RandomnessFulfilledEvent.OutputTuple,
    RandomnessFulfilledEvent.OutputObject
  >;
  getEvent(
    key: "RandomnessRequested"
  ): TypedContractEvent<
    RandomnessRequestedEvent.InputTuple,
    RandomnessRequestedEvent.OutputTuple,
    RandomnessRequestedEvent.OutputObject
  >;
  getEvent(
    key: "RandomnessSourced"
  ): TypedContractEvent<
    RandomnessSourcedEvent.InputTuple,
    RandomnessSourcedEvent.OutputTuple,
    RandomnessSourcedEvent.OutputObject
  >;

  filters: {
    "RandomnessFulfilled(uint256,uint64)": TypedContractEvent<
      RandomnessFulfilledEvent.InputTuple,
      RandomnessFulfilledEvent.OutputTuple,
      RandomnessFulfilledEvent.OutputObject
    >;
    RandomnessFulfilled: TypedContractEvent<
      RandomnessFulfilledEvent.InputTuple,
      RandomnessFulfilledEvent.OutputTuple,
      RandomnessFulfilledEvent.OutputObject
    >;

    "RandomnessRequested(uint256,uint64,uint256)": TypedContractEvent<
      RandomnessRequestedEvent.InputTuple,
      RandomnessRequestedEvent.OutputTuple,
      RandomnessRequestedEvent.OutputObject
    >;
    RandomnessRequested: TypedContractEvent<
      RandomnessRequestedEvent.InputTuple,
      RandomnessRequestedEvent.OutputTuple,
      RandomnessRequestedEvent.OutputObject
    >;

    "RandomnessSourced(uint256,uint64,uint256,bytes32)": TypedContractEvent<
      RandomnessSourcedEvent.InputTuple,
      RandomnessSourcedEvent.OutputTuple,
      RandomnessSourcedEvent.OutputObject
    >;
    RandomnessSourced: TypedContractEvent<
      RandomnessSourcedEvent.InputTuple,
      RandomnessSourcedEvent.OutputTuple,
      RandomnessSourcedEvent.OutputObject
    >;
  };
}
